#!/bin/bash
# Murmur 协作文件管理测试脚本

echo "🚀 Murmur 协作文件管理测试"
echo "================================"
echo ""
echo "这个测试将演示两个节点如何协作管理共享数据"
echo ""
echo "测试场景："
echo "1. 节点 A 写入数据"
echo "2. 节点 B 读取数据（验证同步）"
echo "3. 节点 B 写入新数据"
echo "4. 节点 A 读取新数据（验证双向同步）"
echo ""
echo "请在两个终端中分别运行："
echo ""
echo "终端 1:"
echo "  cd /Users/admin/data0/private_work/r_lit/crates/murmur"
echo "  cargo run --release --example manual_test"
echo "  输入昵称: Alice"
echo "  输入群组: test_collab"
echo "  等待 10 秒让 LocalSwarmDiscovery 工作"
echo "  执行命令:"
echo "    > write file:readme.md \"# Welcome to Murmur\\nThis is a collaborative file\""
echo "    > write file:config.json \"{\\\"version\\\": \\\"1.0\\\", \\\"author\\\": \\\"Alice\\\"}\""
echo "    > list"
echo ""
echo "终端 2:"
echo "  cd /Users/admin/data0/private_work/r_lit/crates/murmur"
echo "  cargo run --release --example manual_test"
echo "  输入昵称: Bob"
echo "  输入群组: test_collab"
echo "  等待 10 秒连接到 Alice"
echo "  执行命令:"
echo "    > list  # 应该看到 Alice 的连接"
echo "    > read file:readme.md  # 应该看到 Alice 写入的内容"
echo "    > read file:config.json"
echo "    > write file:notes.txt \"Bob's notes: Connection successful!\""
echo ""
echo "回到终端 1 (Alice):"
echo "    > read file:notes.txt  # 应该看到 Bob 写入的内容"
echo "    > list  # 应该看到 Bob 的连接"
echo ""
echo "✅ 如果以上步骤都成功，说明协作功能正常！"
echo ""
echo "高级测试："
echo "  - 同时修改同一个 key（测试 CRDT 冲突解决）"
echo "  - 断开一个节点，另一个继续写入，重新连接后验证同步"
echo "  - 三个或更多节点同时协作"
echo ""
