#!/bin/bash
# 自动化协作测试脚本

set -e

MURMUR_DIR="/Users/admin/data0/private_work/r_lit/crates/murmur"
cd "$MURMUR_DIR"

echo "🚀 Murmur 协作功能自动化测试"
echo "================================"
echo ""

# 清理旧数据
echo "🧹 清理旧测试数据..."
rm -rf /tmp/murmur_manual_test_*
echo "✅ 清理完成"
echo ""

# 构建
echo "🔨 构建 manual_test..."
cargo build --release --example manual_test 2>&1 | tail -1
echo "✅ 构建完成"
echo ""

echo "📝 测试说明："
echo "   这个脚本会指导你手动测试协作功能"
echo "   你需要打开两个终端窗口"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 终端 1 - Alice (数据提供者)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "运行命令:"
echo "  cd $MURMUR_DIR"
echo "  cargo run --release --example manual_test"
echo ""
echo "输入:"
echo "  昵称: Alice"
echo "  群组: collab_test"
echo ""
echo "等待 10 秒后执行:"
echo "  > write doc:readme \"# Murmur Collaboration Test\""
echo "  > write config:app '{\"version\": \"1.0\", \"author\": \"Alice\"}'"
echo "  > write data:counter \"1\""
echo "  > list"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 终端 2 - Bob (数据消费者)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "运行命令:"
echo "  cd $MURMUR_DIR"
echo "  cargo run --release --example manual_test"
echo ""
echo "输入:"
echo "  昵称: Bob"
echo "  群组: collab_test"
echo ""
echo "等待 10 秒后执行:"
echo "  > list  # 应该看到 Alice 已连接"
echo "  > read doc:readme  # 应该看到 Alice 写入的内容"
echo "  > read config:app"
echo "  > read data:counter"
echo "  > write data:counter \"2\"  # 更新计数器"
echo "  > write note:bob \"Bob was here!\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 回到终端 1 - Alice (验证同步)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "执行:"
echo "  > list  # 应该看到 Bob 已连接"
echo "  > read note:bob  # 应该看到 Bob 的消息"
echo "  > read data:counter  # 应该看到更新后的值 \"2\""
echo "  > info  # 查看节点信息和 leader 状态"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 验证要点"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. ✓ LocalSwarmDiscovery 自动发现对方"
echo "2. ✓ 数据写入后自动同步到其他节点"
echo "3. ✓ 双向同步正常工作"
echo "4. ✓ Leader 选举正常（NodeId 较大的成为 leader）"
echo "5. ✓ 连接列表显示所有在线节点"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔬 高级测试（可选）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "测试 CRDT 冲突解决:"
echo "  1. 在两个终端同时执行: write test:conflict \"value_from_X\""
echo "  2. 等待几秒后，两边都执行: read test:conflict"
echo "  3. 验证两边看到的值一致（CRDT 自动解决冲突）"
echo ""
echo "测试离线同步:"
echo "  1. 关闭 Bob (Ctrl+C)"
echo "  2. Alice 继续写入: write offline:test \"written while Bob offline\""
echo "  3. 重新启动 Bob，使用相同的群组"
echo "  4. Bob 执行: read offline:test"
echo "  5. 验证 Bob 能看到离线期间的更新"
echo ""
echo "测试三节点协作:"
echo "  1. 打开第三个终端，启动 Charlie"
echo "  2. 使用相同的群组 ID"
echo "  3. 验证三个节点都能互相看到"
echo "  4. 任意节点写入，其他节点都能读取"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "准备好了吗？按 Enter 继续..."
read

echo ""
echo "✨ 开始测试！请按照上面的说明操作两个终端"
echo ""
