#!/bin/bash

# 简化的 murmur 双进程测试
# 需要手动在两个终端运行

echo "🧪 Murmur 双进程协同编辑测试"
echo "============================"
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 打开两个终端窗口"
echo ""
echo "2. 在终端 1 中运行："
echo "   cd /Users/admin/data0/private_work/r_lit/crates/murmur"
echo "   cargo run --example manual_test"
echo "   输入昵称: Alice"
echo "   输入群组: test_group"
echo ""
echo "3. 在终端 2 中运行："
echo "   cd /Users/admin/data0/private_work/r_lit/crates/murmur"
echo "   cargo run --example manual_test"
echo "   输入昵称: Bob"
echo "   输入群组: test_group"
echo ""
echo "4. 等待两个节点互相发现（应该显示 'Connected to 1 peer'）"
echo ""
echo "5. 在 Alice 终端输入："
echo "   write message Hello from Alice"
echo ""
echo "6. 在 Bob 终端输入："
echo "   read message"
echo "   (应该看到 Alice 写入的内容)"
echo ""
echo "7. 反向测试："
echo "   Bob 写入: write reply Hello from Bob"
echo "   Alice 读取: read reply"
echo ""
echo "预期结果："
echo "  ✅ 两个节点能互相发现"
echo "  ✅ 数据能够同步"
echo ""
